/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimKiemRouteImport } from './routes/tim-kiem'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DanhMucSlugRouteImport } from './routes/danh-muc.$slug'
import { Route as BaiVietSlugRouteImport } from './routes/bai-viet.$slug'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as AdminArticlesIdRouteImport } from './routes/admin.articles.$id'

const TimKiemRoute = TimKiemRouteImport.update({
  id: '/tim-kiem',
  path: '/tim-kiem',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DanhMucSlugRoute = DanhMucSlugRouteImport.update({
  id: '/danh-muc/$slug',
  path: '/danh-muc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BaiVietSlugRoute = BaiVietSlugRouteImport.update({
  id: '/bai-viet/$slug',
  path: '/bai-viet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/tim-kiem': typeof TimKiemRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tim-kiem': typeof TimKiemRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/tim-kiem': typeof TimKiemRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/bai-viet/$slug': typeof BaiVietSlugRoute
  '/danh-muc/$slug': typeof DanhMucSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/tim-kiem'
    | '/admin/categories'
    | '/bai-viet/$slug'
    | '/danh-muc/$slug'
    | '/admin/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tim-kiem'
    | '/admin/categories'
    | '/bai-viet/$slug'
    | '/danh-muc/$slug'
    | '/admin'
    | '/admin/articles/$id'
    | '/admin/articles/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/tim-kiem'
    | '/admin/categories'
    | '/bai-viet/$slug'
    | '/danh-muc/$slug'
    | '/admin/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  TimKiemRoute: typeof TimKiemRoute
  BaiVietSlugRoute: typeof BaiVietSlugRoute
  DanhMucSlugRoute: typeof DanhMucSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tim-kiem': {
      id: '/tim-kiem'
      path: '/tim-kiem'
      fullPath: '/tim-kiem'
      preLoaderRoute: typeof TimKiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/danh-muc/$slug': {
      id: '/danh-muc/$slug'
      path: '/danh-muc/$slug'
      fullPath: '/danh-muc/$slug'
      preLoaderRoute: typeof DanhMucSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bai-viet/$slug': {
      id: '/bai-viet/$slug'
      path: '/bai-viet/$slug'
      fullPath: '/bai-viet/$slug'
      preLoaderRoute: typeof BaiVietSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  TimKiemRoute: TimKiemRoute,
  BaiVietSlugRoute: BaiVietSlugRoute,
  DanhMucSlugRoute: DanhMucSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
